import React, { useEffect, useState } from 'react';
import SmartSelect from '../../shared/components/SmartSelect.jsx';
import { buttonLabel } from '../../shared/buttonLabel.js';
import { fa, formatDate, normalizeDigits } from '../../shared/utils.js';
import { burdenScoreFromAnswers, safeText, validDailyAnswer, validName, validPersianText, validPhone } from './journeyStore.js';

export const SCALE_QUESTIONS = [
  'این مشکل در حال حاضر چقدر شدت دارد؟',
  'این مشکل چقدر در زندگی روزمره تو اختلال ایجاد می‌کند؟',
  'چقدر احساس می‌کنی کنترل این مشکل برایت دشوار است؟',
  'چقدر این مشکل باعث اجتناب، تنش یا واکنش ناخواسته می‌شود؟',
  'چقدر می‌خواهی در این ۲۸ روز روی تغییر آن کار کنی؟',
];

export const GENDER_OPTIONS = [{ value: '', label: 'انتخاب کنید' }, { value: 'زن', label: 'زن' }, { value: 'مرد', label: 'مرد' }, { value: 'ترجیح می‌دهم نگویم', label: 'ترجیح می‌دهم نگویم' }];
export const MEDICAL_OPTIONS = [{ value: '', label: 'انتخاب کنید' }, { value: 'none', label: 'موردی ندارم' }, { value: 'epilepsy', label: 'صرع' }, { value: 'seizure', label: 'سابقه تشنج' }, { value: 'panic', label: 'پانیک' }, { value: 'bipolar', label: 'اختلال دو قطبی' }, { value: 'speech_hearing', label: 'مشکل گفتاری یا شنوایی' }, { value: 'other', label: 'سایر موارد مهم' }];
export const MEDICATION_OPTIONS = [{ value: '', label: 'انتخاب کنید' }, { value: 'no', label: 'خیر' }, { value: 'yes_fixed', label: 'بله، ساعت مصرف مشخص دارد' }, { value: 'yes_flexible', label: 'بله، ساعت مصرف مشخص ندارد' }];
export const RISK_OPTIONS = [{ value: '', label: 'انتخاب کنید' }, { value: 'no', label: 'خیر' }, { value: 'yes', label: 'بله' }, { value: 'unknown', label: 'نمی‌دانم' }];
export const FEEDBACK_OPTIONS = [{ value: '', label: 'انتخاب کنید' }, { value: 'better', label: 'بهتر شدم' }, { value: 'same', label: 'تقریباً مثل قبل' }, { value: 'worse', label: 'بدتر شدم' }, { value: 'hard', label: 'تمرین برایم سخت بود' }];

export function Header({ activeDay = 0 }) {
  const n = Math.max(0, Math.min(28, Number(activeDay) || 0));
  const progress = Math.round((n / 28) * 100);
  return (
    <header className="header">
      <div className="brand">
        <img className="logo" src={`${import.meta.env.BASE_URL}assets/logo.png`} alt="لوگوی مرکز هیپنوتراپی شفا" />
        <div><div className="subtitle">مرکز هیپنوتراپی شفا</div><h1>مسیر ۲۸ روزه بازسازی ذهن</h1><div className="subtitle">یک قدم کوچک، هر روز</div></div>
      </div>
      <div className="progress"><div className="bar" id="bar" style={{ width: `${progress}%` }} /></div>
      <div className="stats"><span id="progressText">روز {fa(n)} از ۲۸</span><span id="percent">{fa(progress)}٪</span></div>
    </header>
  );
}

export function Home({ onStart, onHow }) {
  return <section className="card" id="home"><div className="welcome"><span className="badge">مسیر اختصاصی شما</span><h2>به مسیر ۲۸ روزه بازسازی ذهن خوش آمدید</h2><p className="muted">یک مسیر ساختاریافته برای خودمشاهده، تمرین روزانه و پیگیری تغییرات؛ هر روز فقط یک قدم مشخص.</p><div className="introBox"><b>قبل از شروع</b><br/><span className="muted">ابتدا اطلاعات پرونده و ارزیابی اولیه را ثبت می‌کنی. سپس هر روز یک تمرین و یک اقدام عملی دریافت می‌کنی و نتیجه همان روز را ثبت می‌کنی.</span></div><button className="primary" onClick={onStart}>{buttonLabel('شروع مسیر ۲۸ روزه بازسازی ذهن')}</button><button className="secondary" onClick={onHow}>🌌 مسیر ۲۸ روزه چگونه کار می‌کند؟</button></div></section>;
}

export function HowWorks({ onBack }) {
  return <section className="card" id="howWorks"><span className="badge">راهنمای مسیر</span><h2>مسیر ۲۸ روزه چگونه کار می‌کند؟</h2><div className="introBox"><p><b>۱. ثبت اطلاعات و ارزیابی اولیه</b><br/><span className="muted">اطلاعات لازم را ثبت می‌کنی، مسئله اصلی و وضعیت شروع خودت را مشخص می‌کنی.</span></p><p><b>۲. هر روز یک تمرین و یک اقدام</b><br/><span className="muted">هر روز یک تمرین متناسب با مسیرت و یک اقدام عملی مشخص دریافت می‌کنی.</span></p><p><b>۳. ثبت عملکرد همان روز</b><br/><span className="muted">پس از انجام تمرین، شدت درگیری را از <b>۰ تا ۱۰</b> ثبت می‌کنی و تجربه امروزت را می‌نویسی.</span></p><p><b>۴. بازخورد و تنظیم ادامه مسیر</b><br/><span className="muted">بازخوردهای تو برای تنظیم ادامه مسیر استفاده می‌شوند تا تمرین‌ها متناسب‌تر شوند.</span></p><p><b>۵. یک قدم کوچک در هر روز</b><br/><span className="muted">هدف، تغییر یک‌باره نیست؛ هدف این است که در هر روز یک گام واقعی برداری.</span></p><p><b>۶. ارزیابی نهایی</b><br/><span className="muted">پس از روز <b>۲۸</b>، وضعیت پایان مسیر با نقطه شروع مقایسه می‌شود.</span></p><p><b>۷. گزارش و پیشنهاد ادامه مسیر</b><br/><span className="muted">گزارش نهایی عملکردت را نشان می‌دهد و بر اساس نتیجه و اطلاعات پرونده، پیشنهاد مناسب برای ادامه مسیر ارائه می‌شود.</span></p><p><b>۸. کتابخانه اختصاصی و آرشیو</b><br/><span className="muted">در طول مسیر به سه جلد کتاب و کتابچه تکمیلی داخل برنامه دسترسی داری و پس از پایان مسیر می‌توانی مسیرهای قبلی را در آرشیو ببینی.</span></p></div><button className="primary" onClick={onBack}>{buttonLabel('متوجه شدم و بازمی‌گردم')}</button></section>;
}

export function ProfileScreen({ initial, editing, onSave, onCancel, onValidation }) {
  const [form, setForm] = useState({ name: '', age: '', gender: '', phone: '', medical: '', medicalNote: '', medication: '', medicationRisk: '' });
  useEffect(() => setForm({ name: initial?.name || '', age: initial?.age || '', gender: initial?.gender || '', phone: initial?.phone || '', medical: initial?.medical || '', medicalNote: initial?.medicalNote || '', medication: initial?.medication || '', medicationRisk: initial?.medicationRisk || '' }), [initial]);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  function submit() {
    const name = form.name.trim(), age = Number(normalizeDigits(form.age)), phone = normalizeDigits(form.phone.trim()), missing = [];
    if (!validName(name)) missing.push('نام و نام خانوادگی');
    if (!Number.isInteger(age) || age < 12 || age > 100) missing.push('سن بین ۱۲ تا ۱۰۰');
    if (!form.gender) missing.push('جنسیت');
    if (!validPhone(phone)) missing.push('شماره موبایل ۱۱ رقمی با ۰۹');
    if (!form.medical) missing.push('بیماری یا وضعیت پزشکی');
    if (form.medical === 'other' && !safeText(form.medicalNote, 1000)) missing.push('توضیح سایر بیماری‌ها/وضعیت‌ها');
    if (!form.medication) missing.push('وضعیت مصرف دارو');
    if (!form.medicationRisk) missing.push('خطر احتمالی داروی ساعت‌دار');
    if (missing.length) return onValidation(missing, 'پروفایل هنوز کامل نشده است');
    onSave({ ...form, name, age, phone, medicalNote: form.medicalNote.trim(), updatedAt: new Date().toISOString() });
  }
  return <section className="card" id="profile"><span className="badge">پروفایل من</span><h2>اطلاعات شخصی و ثابت</h2><p className="muted">اطلاعات شخصی تو برای مسیرهای بعدی ذخیره می‌شود. پس از تکمیل اولیه، هر زمان بخواهی می‌توانی آن را ویرایش کنی.</p><div className="sectionHint"><span>۱</span><div><b>پروفایل مستقل</b><small>اطلاعات شخصی از مسئله‌ای که روی آن کار می‌کنی جدا نگه داشته می‌شود.</small></div></div><label>نام و نام خانوادگی</label><input autoComplete="name" id="pName" maxLength={80} placeholder="نام و نام خانوادگی" value={form.name} onChange={(e) => set('name', e.target.value)} /><label>سن</label><input id="pAge" inputMode="numeric" maxLength={3} pattern="[0-9۰-۹٠-٩]{2,3}" placeholder="مثلاً ۳۸" type="text" value={form.age} onChange={(e) => set('age', e.target.value)} /><label>جنسیت</label><SmartSelect id="pGender" value={form.gender} onChange={(v) => set('gender', v)} options={GENDER_OPTIONS} /><label>شماره تماس</label><input autoComplete="tel" id="pPhone" inputMode="numeric" maxLength={11} placeholder="شماره تماس" value={form.phone} onChange={(e) => set('phone', e.target.value)} /><label>بیماری یا وضعیت پزشکی مهم</label><SmartSelect id="pMedical" value={form.medical} onChange={(v) => set('medical', v)} options={MEDICAL_OPTIONS} /><label>توضیح سایر بیماری‌ها/وضعیت‌های مهم</label><textarea className="small" id="pMedicalNote" maxLength={1000} placeholder="در صورت انتخاب سایر موارد، توضیح کوتاه بنویسید." value={form.medicalNote} onChange={(e) => set('medicalNote', e.target.value)} /><label>داروی منظم مصرف می‌کنم</label><SmartSelect id="pMedication" value={form.medication} onChange={(v) => set('medication', v)} options={MEDICATION_OPTIONS} /><label>اگر داروی ساعت‌دار مصرف نشود، آیا احتمال تشدید بیماری/علائم در طول جلسه ۸ ساعته وجود دارد؟</label><SmartSelect id="pMedicationRisk" value={form.medicationRisk} onChange={(v) => set('medicationRisk', v)} options={RISK_OPTIONS} /><button className="primary" onClick={submit}>{editing ? 'ذخیره تغییرات پروفایل' : 'ذخیره پروفایل و ادامه'}</button>{editing && <button className="secondary" id="profileCancelEdit" onClick={onCancel}>بازگشت بدون تغییر</button>}</section>;
}

export function PathSetupScreen({ initial, problems, onSave, onEditProfile, onValidation }) {
  const [form, setForm] = useState({ problem: '', durationYears: 0, durationMonths: 0, goal: '' });
  useEffect(() => setForm({ problem: initial?.problem || '', durationYears: initial?.durationYears ?? 0, durationMonths: initial?.durationMonths ?? 0, goal: initial?.goal || '' }), [initial]);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  function submit() {
    const missing = [];
    if (!form.problem) missing.push('مهم‌ترین مسئله');
    if (!safeText(form.goal, 1000)) missing.push('نتیجه ارزشمند مورد انتظار');
    if (Number(form.durationYears) < 0 || Number(form.durationMonths) < 0 || Number(form.durationMonths) > 11) missing.push('مدت درگیری');
    if (missing.length) return onValidation(missing, 'اطلاعات مسیر هنوز کامل نشده است');
    onSave({ problem: form.problem, durationYears: Number(form.durationYears), durationMonths: Number(form.durationMonths), goal: form.goal.trim() });
  }
  const years = Array.from({ length: 31 }, (_, i) => ({ value: String(i), label: i === 0 ? 'کمتر از یک سال' : `${i} سال` }));
  const months = Array.from({ length: 12 }, (_, i) => ({ value: String(i), label: i === 0 ? 'بدون ماه اضافه' : `${i} ماه` }));
  return <section className="card" id="pathSetup"><span className="badge">مسیر جدید · مرحله دوم</span><h2>موضوع این مسیر</h2><p className="muted">پروفایل تو ثابت می‌ماند؛ برای هر مسئله می‌توانی یک مسیر ۲۸ روزه مستقل بسازی.</p><div className="sectionHint"><span>۲</span><div><b>انتخاب مسئله</b><small>این اطلاعات فقط به مسیر فعلی تعلق دارد و در آرشیو همان مسیر ذخیره می‌شود.</small></div></div><label>مهم‌ترین مسئله‌ای که می‌خواهی روی آن کار کنی</label><SmartSelect id="pProblem" value={form.problem} onChange={(v) => set('problem', v)} options={[{ value: '', label: 'انتخاب کنید' }, ...problems.map((p) => ({ value: p, label: p }))]} /><div className="durationGrid"><div><label>مدت درگیری · سال</label><SmartSelect id="pDurationYears" value={String(form.durationYears)} onChange={(v) => set('durationYears', v)} options={years} /></div><div><label>مدت درگیری · ماه</label><SmartSelect id="pDurationMonths" value={String(form.durationMonths)} onChange={(v) => set('durationMonths', v)} options={months} /></div></div><label>از این مسیر چه نتیجه‌ای برای خودت ارزشمند می‌دانی؟</label><textarea className="small" id="pGoal" maxLength={1000} placeholder="در پایان این مسیر دوست دارم..." value={form.goal} onChange={(e) => set('goal', e.target.value)} /><button className="primary" onClick={submit}>{buttonLabel('ادامه به ارزیابی اولیه')}</button><button className="secondary" onClick={onEditProfile}>مشاهده یا ویرایش پروفایل</button></section>;
}

function AssessmentScale({ prefix, values, setValues }) {
  const selected = values.filter((v) => v !== '' && v != null).length;
  const complete = selected === 5;
  const burden = complete ? burdenScoreFromAnswers(values.map(Number)) : null;
  const motivation = complete ? Number(values[4]) : null;
  return <>{SCALE_QUESTIONS.map((question, qIndex) => <div className="scaleQuestion" key={`${prefix}-${qIndex}`}><div className="scaleQuestionTitle"><b>{qIndex + 1}.</b><span>{question}</span></div><div className="scaleOptions" role="group" aria-label={question}>{[0,1,2,3,4].map((n) => <button type="button" key={n} className={`scaleOption ${Number(values[qIndex]) === n && values[qIndex] !== '' ? 'selected' : ''}`} data-scale={`${prefix}-${qIndex + 1}`} data-value={n} aria-pressed={Number(values[qIndex]) === n && values[qIndex] !== '' ? 'true' : 'false'} onClick={() => setValues(values.map((v, i) => i === qIndex ? n : v))}>{n}</button>)}</div><div className="scaleLegend"><span>۰ = اصلاً</span><span>۴ = بسیار زیاد</span></div><input id={`${prefix}Q${qIndex + 1}`} type="hidden" value={values[qIndex]} readOnly data-touched={values[qIndex] === '' ? '0' : '1'} /></div>)}<div className={`assessmentSummary ${complete ? 'complete' : ''}`} id={`${prefix}ScaleSummary`}>{complete ? `ارزیابی کامل است · شاخص شدت: ${fa(burden)} از ۱۰ · انگیزه تغییر: ${fa(motivation)} از ۴` : `${fa(selected)} از ۵ پاسخ انتخاب شده`}</div><input id={`${prefix}Score`} type="hidden" value={complete ? burden : 0} readOnly data-touched={complete ? '1' : '0'} /></>;
}

export function AssessmentScreen({ initial, onSave, onValidation }) {
  const [values, setValues] = useState(() => Array.isArray(initial) && initial.length === 5 ? initial : ['', '', '', '', '']);
  useEffect(() => setValues(Array.isArray(initial) && initial.length === 5 ? initial : ['', '', '', '', '']), [initial]);
  function submit() {
    if (values.some((v) => v === '')) return onValidation(values.map((v, i) => v === '' ? `سؤال ${fa(i + 1)} ارزیابی اولیه` : null).filter(Boolean), 'ارزیابی اولیه هنوز کامل نشده است');
    onSave(values.map(Number));
  }
  return <section className="card assessmentCard" id="assessment"><span className="badge">روز صفر · ارزیابی اولیه</span><h2>نقطه شروع مسیر را ثبت کن</h2><p className="muted">این ۵ سؤال همان خط پایه مسیر هستند. پاسخ درست یا غلطی وجود ندارد؛ فقط وضعیت واقعی امروزت را از ۰ تا ۴ انتخاب کن تا در پایان روز ۲۸ بتوانیم تغییر را دقیق مقایسه کنیم.</p><div className="assessmentIntro"><span>۰</span><div><b>اصلاً / بسیار کم</b><small>هرچه عدد به ۴ نزدیک‌تر شود، شدت یا میزان تجربه بیشتر است.</small></div><span>۴</span></div><AssessmentScale prefix="a" values={values} setValues={setValues} /><button className="primary heroAction" onClick={submit}>{buttonLabel('ثبت ارزیابی و شروع روز ۱')}</button></section>;
}

export function Dashboard({ journey, userProfile, onEditProfile, onCurrent, onBooks, onArchive, onSupport, onChannel }) {
  const p = journey.profileData || {}, u = userProfile || p, next = nextRequiredDayLocal(journey), pct = Math.round((journey.completed.length / 28) * 100);
  return <section className="card" id="dashboard"><div className="dashboardHero"><div><span className="badge">داشبورد شخصی</span><h2 id="dashTitle">مسیر «{p.problem || 'بدون عنوان'}»</h2><p className="muted dashboardLead" id="dashLead">{next > 28 ? '۲۸ روز کامل شده؛ ارزیابی نهایی آماده است.' : `قدم بعدی: روز ${fa(next)} از ۲۸`}</p></div><button aria-label="ویرایش پروفایل" className="iconButton" onClick={onEditProfile}>✎</button></div><div id="profileSummary"><div className="profile"><div className="profileBox"><span>پروفایل</span><b>{u?.name || '-'}</b></div><div className="profileBox"><span>کد مراجع</span><b>{p.code || '-'}</b></div><div className="profileBox"><span>مسئله این مسیر</span><b>{p.problem || '-'}</b></div><div className="profileBox"><span>مدت درگیری</span><b>{fa(p.durationYears || 0)} سال و {fa(p.durationMonths || 0)} ماه</b></div></div></div><div className="metric"><div className="metricBox"><strong id="dashProgress">{fa(pct)}٪</strong><span>پیشرفت مسیر</span></div><div className="metricBox"><strong id="dashDays">{fa(journey.completed.length)}/۲۸</strong><span>روز تکمیل‌شده</span></div></div><button className="primary heroAction" onClick={onCurrent}>{buttonLabel('ادامه مسیر امروز')}</button><div className="quickGrid"><button className="quickAction" onClick={onBooks}><span>📚</span><b>کتابخانه</b><small>مطالعه هدفمند</small></button><button className="quickAction" onClick={onArchive}><span>🗂️</span><b>آرشیو</b><small>مسیرهای قبلی</small></button><button className="quickAction" onClick={onSupport}><span>💬</span><b>پشتیبانی</b><small>ارتباط با مرکز</small></button><button className="quickAction" onClick={onChannel}><span>📣</span><b>کانال مرکز</b><small>محتوای تکمیلی</small></button></div><p className="muted dashboardNote">هر روز فقط یک مرحله اصلی داری. نتیجه روز بعد از انجام تمرین باز می‌شود تا صفحه خلوت و متمرکز بماند.</p></section>;
}

function nextRequiredDayLocal(state) { for (let i = 1; i <= 28; i += 1) if (!(state.completed || []).includes(i)) return i; return 29; }
export function splitDayContent(d) { const raw = String(d?.exercise || ''), mark = 'اقدام اختصاصی امروز:', method = 'روش اختصاصی این مسئله:'; let exercise = String(d?.exerciseText || '').trim(); if (!exercise && raw) exercise = raw.includes(mark) ? raw.split(mark)[0].trim() : raw.split(method)[0].trim(); const title = String(d?.title || 'موضوع امروز').split('·')[0].trim(); const a = String(d?.actionText || '').trim(); const action = (a ? `در «${title}»، یک موقعیت واقعی و امن از امروز را انتخاب کن؛ مثلاً همان موقعیتی که این اقدام برایت معنا دارد. آن موقعیت را مشخص کن، «${a}» را همان‌جا اجرا کن و بعد نتیجه را در پاسخ امروزت بنویس.` : `امروز در یک موقعیت واقعی مرتبط با «${title}»، یک کار کوچک و مشخص انتخاب کن، انجامش بده و نتیجه را ثبت کن.`).replace(/^مثال عینی\s*:\s*/i, '').trim(); return { exercise, action, title }; }
export function severityText(n) { return n <= 2 ? '۰ تا ۲ = بسیار کم یا تقریباً بدون درگیری' : n <= 4 ? '۳ تا ۴ = خفیف' : n <= 6 ? '۵ تا ۶ = متوسط' : n <= 8 ? '۷ تا ۸ = زیاد' : '۹ تا ۱۰ = بسیار شدید و درگیرکننده'; }

export function DayScreen({ day, problem, data, record, savedAnswer, onDashboard, onPrevious, onComplete, onNext, completed, onValidation }) {
  const parts = splitDayContent(data), [entryOpen, setEntryOpen] = useState(Boolean(record?.score != null || savedAnswer || record?.feedback)), [score, setScore] = useState(record?.score ?? 0), [touched, setTouched] = useState(record?.score != null), [feedback, setFeedback] = useState(record?.feedback || ''), [answer, setAnswer] = useState(savedAnswer || '');
  useEffect(() => { setEntryOpen(Boolean(record?.score != null || savedAnswer || record?.feedback)); setScore(record?.score ?? 0); setTouched(record?.score != null); setFeedback(record?.feedback || ''); setAnswer(savedAnswer || ''); }, [day, record, savedAnswer]);
  if (!data) return null;
  const bubblePos = Math.min(96, Math.max(4, (10 - Number(score)) * 10));
  function submit() { const missing = []; if (!touched || Number(score) < 0 || Number(score) > 10) missing.push('شدت یا میزان درگیری از ۰ تا ۱۰'); if (!feedback) missing.push('بازخورد امروز'); if (!validDailyAnswer(answer)) missing.push('پاسخ یا تجربه امروز (فقط کلمات فارسی و نشانه‌های مجاز)'); if (missing.length) return onValidation(missing, 'نتیجه امروز هنوز کامل نشده است'); onComplete({ answer: answer.trim(), score: Number(score), feedback }); }
  return <section className="card dayCard" id="day"><div className="dayTopline"><span className="badge" id="dayBadge">روز {fa(day)} از ۲۸ · {problem}</span><button aria-label="داشبورد" className="iconButton subtle" onClick={onDashboard}>⌂</button></div><h2 id="dayTitle">{parts.title}</h2><p className="muted" id="dayIntro">امروز روی «{parts.title}» تمرکز می‌کنی.</p><div className="dailyStep"><span className="stepNumber">۱</span><div className="exercise"><b>تمرین امروز</b><br/><span id="dayExercise">{parts.exercise}</span></div></div><div className="dailyStep"><span className="stepNumber">۲</span><div className="action"><b>اقدام اختصاصی امروز</b><br/><span id="dayAction">{parts.action}</span></div></div><div className="safetyNote"><span>◌</span><p className="muted" id="dayClosing">{data.closing || ''}</p></div>{!entryOpen && <button className="primary heroAction" id="openDailyEntryBtn" onClick={() => setEntryOpen(true)}>انجام دادم؛ ثبت نتیجه امروز</button>}{entryOpen && <div aria-live="polite" className="dailyEntryPanel" id="dailyEntryPanel"><div className="entryHeader"><span className="stepNumber">۳</span><div><b>ثبت نتیجه</b><small>کمتر از یک دقیقه</small></div></div><label>شدت یا میزان درگیری امروز</label><div className="severityWrap"><div className="severityValue" id="severityValue" style={{ left: `${bubblePos}%` }}>{touched ? `${fa(score)} از ۱۰` : 'انتخاب نشده'}</div><div className="severityThumb" id="severityThumb" /><input aria-label="شدت درگیری" className="severityRange" id="dayScore" max="10" min="0" step="1" type="range" value={score} data-touched={touched ? '1' : '0'} onChange={(e) => { setScore(Number(e.target.value)); setTouched(true); }} /></div><div className="stats" style={{ color: 'var(--muted)', marginTop: 0 }}><span>۰ = بدون درگیری</span><span>۵ = متوسط</span><span>۱۰ = بسیار شدید</span></div><p className="muted" id="severityText" style={{ fontSize: 11, marginTop: 5 }}>{severityText(Number(score))}</p><label>بازخورد امروز</label><SmartSelect id="dayFeedbackChoice" value={feedback} onChange={setFeedback} options={FEEDBACK_OPTIONS} /><label>پاسخ یا تجربه امروزت</label><textarea id="answer" maxLength={3000} placeholder="کوتاه و واقعی بنویس؛ چه اتفاقی افتاد و چه چیزی یاد گرفتی؟" value={answer} onChange={(e) => setAnswer(e.target.value)} /><button className="primary" onClick={submit}>{buttonLabel('ثبت امروز و دریافت نتیجه')}</button><button className="ghostButton" onClick={() => setEntryOpen(false)}>فعلاً می‌خواهم تمرین را ادامه بدهم</button></div>}<div className="feedback hidden" id="dailyFeedback"/><div className="recommendation hidden" id="dailyRecommendation"/><div className="navrow compactNav"><button className="secondary" onClick={onPrevious}>{buttonLabel('روز قبل')}</button><button className="secondary" onClick={onDashboard}>{buttonLabel('داشبورد')}</button></div><div id="nextButtonWrap">{day < 28 && completed && <button className="primary" onClick={onNext}>ادامه به روز {fa(day + 1)}</button>}</div></section>;
}

export function nextStepText(n, d, rec) { const title = String(d?.title || 'این مرحله').split('·')[0].trim(), action = String(d?.actionText || '').trim(), phase = n <= 7 ? 'حالا مهم‌ترین کار، دیدن الگوی امروز بدون عجله است.' : n <= 14 ? 'حالا وقت آن است که آگاهی امروز را به یک رفتار کوچک تبدیل کنی.' : n <= 21 ? 'در این مرحله، تکرار آگاهانه مهارت‌ها از فشار آوردن به خودت مهم‌تر است.' : 'روزهای پایانی برای تثبیت آموخته‌ها و ساختن قدم بعدی توست.', feedback = rec?.feedback === 'better' ? 'بهبودی امروز را دقیق ببین و مشخص کن چه چیزی به آن کمک کرد.' : rec?.feedback === 'worse' ? 'امروز فشار را بیشتر نکن؛ شدت را مدیریت کن و اگر لازم است کمک حرفه‌ای بگیر.' : rec?.feedback === 'hard' ? 'اگر تمرین سخت بود، آن را کوچک‌تر کن اما ارتباطت را با مسیر حفظ کن.' : 'تجربه امروز را مرور کن و فقط یک نکته قابل استفاده با خودت نگه دار.'; return `روز ${fa(n)} روی «${title}» تمرکز داشت. ${phase} ${feedback} ${action ? `برای ادامه، همین مهارت را در یک موقعیت امن دیگر امتحان کن: «${action}»` : 'فردا با مرحله بعدی ادامه بده.'}`; }

export function DailyResult({ day, journey, data, sourceLabel, onDashboard, onNext, onFinal, onBook }) {
  const rec = journey.daily?.[day] || {}, labels = { better: 'بهتر شدم', same: 'تقریباً مثل قبل', worse: 'بدتر شدم', hard: 'تمرین برایم سخت بود' };
  return <section className="card" id="dailyResult"><span className="badge" id="resultBadge">نتیجه روز {fa(day)} از ۲۸</span><h2 id="resultTitle">عملکرد روز {fa(day)}</h2><div className="metric"><div className="metricBox"><strong id="resultScore">{fa(rec.score)}/۱۰</strong><span>امتیاز امروز</span></div><div className="metricBox"><strong id="resultFeedback">{labels[rec.feedback] || 'ثبت شد'}</strong><span>بازخورد</span></div></div><div className="feedback"><b>جمع‌بندی امروز</b><p className="muted" id="resultText">{rec.feedbackText}</p></div><div className="recommendation"><b>قدم بعدی</b><p className="muted" id="resultNext">{day === 28 ? 'روز ۲۸ کامل شد. اکنون ارزیابی نهایی فعال است.' : nextStepText(day, data, rec)}</p></div><div id="resultNextWrap">{data?.bookRec && <><div className="bookRecommendationSource">{sourceLabel}</div><button className="gold" onClick={() => onBook(data.bookRec)}>📖 مطالعه پیشنهاد کتاب امروز</button></>}{day === 28 ? <button className="primary" onClick={onFinal}>رفتن به ارزیابی نهایی →</button> : <button className="primary" onClick={() => onNext(day + 1)}>رفتن به روز {fa(day + 1)} →</button>}</div><div className="navrow"><button className="secondary" onClick={onDashboard}>{buttonLabel('بازگشت به داشبورد')}</button></div></section>;
}

export function Support({ content, onBack }) {
  const [help, setHelp] = useState('اگر اپ شما اجازه باز کردن مستقیم پیامک را ندهد، شماره با یک لمس کپی می‌شود.');
  const number = '09190889062';
  function legacyCopy(text, done) { const ta = document.createElement('textarea'); ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0'; document.body.appendChild(ta); ta.select(); try { document.execCommand('copy'); done?.(); } catch { /* noop */ } ta.remove(); }
  function copySupportNumber() { const done = () => setHelp('شماره ۰۹۱۹۰۸۸۹۰۶۲ کپی شد.'); if (navigator.clipboard && window.isSecureContext) navigator.clipboard.writeText(number).then(done).catch(() => legacyCopy(number, done)); else legacyCopy(number, done); }
  function sendSms() { const body = 'سلام، برای نوبت‌دهی و دریافت راهنمایی پیام می‌دهم.'; try { if (window.Android && typeof window.Android.openSms === 'function') { window.Android.openSms(number, body); setHelp('برنامه پیامک باز شد.'); return; } if (window.webkit?.messageHandlers?.openSms) { window.webkit.messageHandlers.openSms.postMessage({ number, body }); setHelp('برنامه پیامک باز شد.'); return; } const ua = navigator.userAgent || '', sep = /iPhone|iPad|iPod/i.test(ua) ? '&' : '?', a = document.createElement('a'); a.href = `sms:${number}${sep}body=${encodeURIComponent(body)}`; a.style.display = 'none'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => setHelp('اگر پیامک باز نشد، «کپی شماره» را بزنید. در WebView اپ باید scheme پیامک به سیستم تحویل داده شود.'), 900); } catch { copySupportNumber(); } }
  return <section className="card" id="support"><span className="badge">پشتیبانی مرکز</span><h2>نیاز به راهنمایی داری؟</h2><p className="muted">اگر در انجام تمرین‌ها، ادامه مسیر یا استفاده از برنامه نیاز به راهنمایی داری، می‌توانی با مرکز هیپنوتراپی شفا ارتباط بگیری.</p><div className="support"><h3>📱 نوبت‌دهی پیامکی</h3><p className="muted">شماره مرکز: <b>۰۹۱۹۰۸۸۹۰۶۲</b></p><div className="contactActions"><button className="sms" onClick={sendSms}>باز کردن پیامک</button><button className="copyAction" onClick={copySupportNumber}>کپی شماره</button></div><p className="contactHelp" id="smsHelp">{help}</p><hr/><h3>💬 نوبت‌دهی تلگرامی</h3><p className="muted">پشتیبانی و نوبت‌دهی تلگرامی مرکز</p><a className="telegram" href={content.supportUrl || content.bookSupportUrl || 'https://t.me/Hypnotherapy_admin'} rel="noopener" target="_blank">ورود به پشتیبانی تلگرام</a></div><button className="secondary" onClick={onBack}>{buttonLabel('بازگشت')}</button></section>;
}

function reflectionValues(value) { const rows = String(value || '').split('\n---\n').slice(0, 3); return [...rows, '', '', ''].slice(0, 3); }
function ReflectionFields({ prefix, values, setValues }) { return <>{values.map((value, i) => <textarea key={`${prefix}-${i}`} className="small" id={`${prefix}_${i + 1}`} maxLength={2000} placeholder={`مورد ${fa(i + 1)} را بنویس...`} value={value} onChange={(e) => setValues(values.map((row, j) => j === i ? e.target.value : row))} />)}</>; }

export function FinalAssessment({ initial, onSave, onValidation }) {
  const [values, setValues] = useState(() => Array.isArray(initial?.answers) ? initial.answers : ['', '', '', '', '']), [changes, setChanges] = useState(() => reflectionValues(initial?.f1)), [awareness, setAwareness] = useState(() => reflectionValues(initial?.f2)), [actions, setActions] = useState(() => reflectionValues(initial?.f3)), [remaining, setRemaining] = useState(initial?.f4 || '');
  useEffect(() => { setValues(Array.isArray(initial?.answers) ? initial.answers : ['', '', '', '', '']); setChanges(reflectionValues(initial?.f1)); setAwareness(reflectionValues(initial?.f2)); setActions(reflectionValues(initial?.f3)); setRemaining(initial?.f4 || ''); }, [initial]);
  function submit() { const missing = []; if (values.some((v) => v === '')) missing.push('پنج سؤال ارزیابی نهایی'); if (changes.some((v) => !validPersianText(v))) missing.push('سه تغییر واقعی'); if (awareness.some((v) => !validPersianText(v))) missing.push('سه آگاهی مهم'); if (actions.some((v) => !validPersianText(v))) missing.push('سه اقدام ۳۰ روز آینده'); if (!validPersianText(remaining)) missing.push('مهم‌ترین موضوع نیازمند کار'); if (missing.length) return onValidation(missing, 'ارزیابی نهایی هنوز کامل نشده است'); onSave({ answers: values.map(Number), changes: changes.map((v) => v.trim()), awareness: awareness.map((v) => v.trim()), actions: actions.map((v) => v.trim()), remaining: remaining.trim() }); }
  const one = [{ value: '3', label: '۳ مورد' }];
  return <section className="card assessmentCard" id="final"><span className="badge">روز ۲۸ · ارزیابی نهایی</span><h2>مسیر را کامل کردی؛ حالا تغییر را اندازه بگیر</h2><p className="muted">همان ۵ سؤال شروع مسیر را دوباره پاسخ بده تا مقایسه قبل و بعد معنی‌دار و قابل فهم باشد.</p><AssessmentScale prefix="f" values={values} setValues={setValues} /><div className="finalReflection"><h3>جمع‌بندی کوتاه مسیر</h3><label>سه تغییر واقعی که در خودم مشاهده کردم</label><SmartSelect id="f1Count" value="3" onChange={() => {}} options={one}/><div id="f1Fields"><ReflectionFields prefix="f1" values={changes} setValues={setChanges}/></div><label>سه آگاهی مهمی که به دست آوردم</label><SmartSelect id="f2Count" value="3" onChange={() => {}} options={one}/><div id="f2Fields"><ReflectionFields prefix="f2" values={awareness} setValues={setAwareness}/></div><label>سه اقدام مشخص برای ۳۰ روز آینده</label><SmartSelect id="f3Count" value="3" onChange={() => {}} options={one}/><div id="f3Fields"><ReflectionFields prefix="f3" values={actions} setValues={setActions}/></div><label>مهم‌ترین چیزی که هنوز نیاز به کار دارد</label><textarea className="small" id="f4" maxLength={2000} value={remaining} onChange={(e) => setRemaining(e.target.value)} /></div><button className="primary heroAction" onClick={submit}>{buttonLabel('ثبت ارزیابی نهایی')}</button></section>;
}

export function Done({ onReport, onBooks, onSupport, onArchive, onNew }) { return <section className="card" id="done"><div className="welcome"><span className="badge">مسیر تکمیل شد</span><h2>۲۸ روز را به پایان رساندی.</h2><p className="muted">پایان این برنامه، پایان یادگیری نیست؛ شروع مرحله‌ای است که باید آگاهی‌ها را به رفتارهای پایدار تبدیل کنی.</p><button className="primary" onClick={onReport}>📊 مشاهده گزارش نهایی</button><button className="gold" onClick={onBooks}>📚 کتابخانه اختصاصی</button><button className="secondary" onClick={onSupport}>☎️ ارتباط با مرکز</button><button className="secondary" onClick={onArchive}>🗂 آرشیو مسیرهای قبلی</button><button className="primary" onClick={onNew}>{buttonLabel('شروع مسیر تازه →')}</button></div></section>; }

export function buildFinalAnalysis(s) { const days = []; for (let i = 1; i <= 28; i += 1) if (s.daily?.[i]) days.push({ ...s.daily[i], day: i }); const scores = days.map((x) => Number(x.score)).filter(Number.isFinite), counts = { better: 0, same: 0, worse: 0, hard: 0 }; days.forEach((x) => { if (counts[x.feedback] !== undefined) counts[x.feedback] += 1; }); const avg = scores.length ? scores.reduce((a, b) => a + b, 0) / scores.length : 0, first = Number(s.daily?.[1]?.score), last = Number(s.daily?.[28]?.score); return { count: days.length, avg, first: Number.isFinite(first) ? first : null, last: Number.isFinite(last) ? last : null, improvement: Number.isFinite(first) && Number.isFinite(last) ? first - last : 0, counts, persistent: days.filter((x) => Number(x.score) >= 7).length, assessmentStart: Number(s.assessmentData?.score || 0), finalScore: Number(s.final?.score || 0), problem: s.profileData?.problem || '', age: s.profileData?.age || '', medical: s.profileData?.medical || '', medication: s.profileData?.medication || '', medicationRisk: s.profileData?.medicationRisk || '' }; }
function hypnoEligibility(p) { const reasons = []; if (!p || !Number.isInteger(Number(p.age))) reasons.push('سن ثبت نشده است'); else if (Number(p.age) < 23 || Number(p.age) > 63) reasons.push('سن خارج از محدوده مجاز PQHT (۲۳ تا ۶۳ سال)'); const blocked = { epilepsy: 'صرع', seizure: 'سابقه تشنج', panic: 'پانیک', bipolar: 'اختلال دو قطبی', speech_hearing: 'مشکل گفتاری یا شنوایی' }; if (blocked[p.medical]) reasons.push(blocked[p.medical]); if (p.medication === 'yes_fixed' && ['yes', 'unknown'].includes(p.medicationRisk)) reasons.push(p.medicationRisk === 'yes' ? 'داروی ساعت‌دار که نخوردن آن ممکن است در جلسه ۸ ساعته باعث تشدید بیماری/علائم شود' : 'وضعیت خطر داروی ساعت‌دار برای جلسه ۸ ساعته نامشخص است'); if (p.medical === 'other' && p.medicalNote) reasons.push('سابقه/وضعیت پزشکی دیگری ثبت شده که نیازمند بررسی تخصصی است'); return { eligible: reasons.length === 0, reasons }; }
function Recommendation({ journey }) { const p = journey.profileData || {}, r = hypnoEligibility(p), a = buildFinalAnalysis(journey), trend = a.improvement > 0 ? `امتیاز شدت درگیری از ${fa(a.first)} به ${fa(a.last)} رسیده است.` : a.improvement < 0 ? `امتیاز شدت درگیری از ${fa(a.first)} به ${fa(a.last)} رسیده و نیاز به توجه بیشتری دارد.` : 'امتیاز شدت درگیری در ابتدا و انتهای مسیر تغییر محسوسی نداشته است.'; return <div className="recommendation"><b>🎯 پیشنهاد ادامه مسیر</b><br/>{r.eligible ? <><span>بر اساس <b>اطلاعات ثبت پرونده، ارزیابی اولیه، بازخوردهای تمام {fa(a.count)} روز، شدت‌های ثبت‌شده و ارزیابی نهایی</b>، ادامه مسیر با <b>جلسات مشاوره آنلاین به همراه ارزیابی و در صورت تأیید نهایی درمانگر، جلسه هیپنوتراپی PQHT</b> پیشنهاد می‌شود.</span><br/><span className="muted">{trend}</span><br/><small>این پیشنهاد غربالگری برنامه است و تصمیم نهایی درباره انجام جلسه PQHT فقط پس از ارزیابی تخصصی مرکز گرفته می‌شود.</small></> : <><span>بر اساس <b>اطلاعات ثبت پرونده، ارزیابی اولیه، بازخوردهای تمام {fa(a.count)} روز و ارزیابی نهایی</b>، در حال حاضر <b>جلسات مشاوره آنلاین</b> پیشنهاد می‌شود و جلسه PQHT بدون بررسی تخصصی پیشنهاد نمی‌شود.</span><br/><b>دلیل:</b> {r.reasons.join('، ')}<br/><span className="muted">{trend}</span><br/><small>این سامانه تشخیص پزشکی نمی‌دهد و جایگزین ارزیابی تخصصی نیست.</small></>}</div>; }

export function Report({ journey, content, onBooks, onSupport, onDashboard, onArchive, onNew }) { const p = journey.profileData || {}, a = buildFinalAnalysis(journey), start = Number(journey.assessmentData?.score || 0), end = Number(journey.final?.score || 0), diff = end - start, f = journey.final || {}, cat = content.categories?.[p.problem]; return <section className="card" id="report"><span className="badge">گزارش نهایی مسیر</span><h2>گزارش شخصی مسیر ۲۸ روزه</h2><div id="reportProfile"><div className="profile"><div className="profileBox"><span>نام</span><b>{p.name || ''}</b></div><div className="profileBox"><span>مسئله</span><b>{p.problem || ''}</b></div><div className="profileBox"><span>سن</span><b>{fa(p.age || 0)} سال</b></div></div></div><div className="metric"><div className="metricBox"><strong id="startScore">{fa(start)}/۱۰</strong><span>امتیاز شروع</span></div><div className="metricBox"><strong id="endScore">{fa(end)}/۱۰</strong><span>امتیاز پایان</span></div></div><div className="feedback"><b>نتیجه تغییر</b><p className="muted" id="scoreChange">{diff > 0 ? `امتیاز وضعیت کلی ${fa(diff)} نمره بالاتر شده است.` : diff < 0 ? `امتیاز وضعیت کلی ${fa(Math.abs(diff))} نمره پایین‌تر شده است.` : 'امتیاز وضعیت کلی تغییر نکرده است.'}</p></div><div className="recommendation"><b>جمع‌بندی مسیر</b><p className="muted" id="reportSummary">مسیر ۲۸ روزه برای «{p.problem || ''}» کامل شد. از {fa(a.count)} بازخورد ثبت‌شده، {fa(a.counts.better)} مورد «بهتر شدم»، {fa(a.counts.same)} مورد «تقریباً مثل قبل»، {fa(a.counts.worse)} مورد «بدتر شدم» و {fa(a.counts.hard)} مورد «تمرین برایم سخت بود» ثبت شده است. میانگین شدت درگیری روزانه {fa(Math.round(a.avg * 10) / 10)} از ۱۰ بوده است.</p></div><div id="hypnoReportRecommendation"><Recommendation journey={journey}/></div><hr/><ReportBlock title="سه تغییر من" id="rf1" text={f.f1}/><ReportBlock title="سه آگاهی من" id="rf2" text={f.f2}/><ReportBlock title="سه اقدام ۳۰ روز آینده" id="rf3" text={f.f3}/><ReportBlock title="موضوع نیازمند توجه" id="rf4" text={f.f4}/><hr/><h3>پاسخ‌های ثبت‌شده</h3><div id="answersList">{Object.entries(journey.answers || {}).sort(([x], [y]) => Number(x) - Number(y)).map(([d, ans]) => { const day = cat?.days?.find((x) => Number(x.day) === Number(d)); return <div className="answerItem" key={d}><b>روز {fa(d)} · {day?.title || ''}</b><p>{ans}</p><small>شدت: {fa(journey.daily?.[d]?.score ?? 0)} از ۱۰ · بازخورد: {journey.daily?.[d]?.feedbackText || ''}</small></div>; })}</div><button className="gold" onClick={onBooks}>📚 کتابخانه اختصاصی</button><button className="secondary" onClick={onSupport}>☎️ پشتیبانی مرکز</button><button className="secondary" onClick={onDashboard}>{buttonLabel('بازگشت به داشبورد')}</button><button className="secondary" onClick={onArchive}>🗂 آرشیو مسیرهای قبلی</button><button className="primary" onClick={onNew}>{buttonLabel('شروع مسیر تازه →')}</button></section>; }
function ReportBlock({ title, id, text }) { return <><h3>{title}</h3><div className="answerItem"><p id={id} style={{ whiteSpace: 'pre-wrap' }}>{text || ''}</p></div></>; }

export function Archive({ journey, content, onBack, onNew }) { const [selected, setSelected] = useState(null), list = journey.archive || []; const selectedArchive = selected == null ? null : list[selected]; return <section className="card" id="archive"><span className="badge">آرشیو مسیرها</span><h2>مسیرهای قبلی</h2><p className="muted">هر بار که مسیر تازه‌ای شروع شود، پرونده مسیر قبلی اینجا نگهداری می‌شود.</p><div id="archiveList" className={selectedArchive ? 'hidden' : ''}>{!list.length ? <div className="muted">هنوز مسیر قبلی در آرشیو وجود ندارد.</div> : list.map((a, i) => { const p = a.profileData || {}, completed = Array.isArray(a.completed) ? a.completed.length : 0; return <div className="answerItem" key={`${a.pathId}-${i}`}><b>مسیر {fa(i + 1)} · {p.problem || 'بدون عنوان'}</b><p>پیشرفت: {fa(completed)}/۲۸ · امتیاز شروع: {a.assessmentData?.score == null ? '-' : `${fa(a.assessmentData.score)}/۱۰`} · امتیاز پایان: {a.final?.score == null ? '-' : `${fa(a.final.score)}/۱۰`}<br/>تاریخ شروع: {formatDate(a.startedAt)}<br/>تاریخ بایگانی: {formatDate(a.archivedAt)}</p><button className="secondary" onClick={() => { setSelected(i); window.scrollTo({ top: 0, behavior: 'auto' }); }}>👁️ مشاهده جزئیات مسیر</button></div>; })}</div><div id="archiveDetail" className={selectedArchive ? '' : 'hidden'}>{selectedArchive && <ArchiveDetail archive={selectedArchive} content={content} onClose={() => setSelected(null)} />}</div><button className="primary" onClick={onNew}>{buttonLabel('شروع مسیر تازه →')}</button><button className="secondary" onClick={onBack}>{buttonLabel('بازگشت به داشبورد')}</button></section>; }
function ArchiveDetail({ archive, content, onClose }) { const p = archive.profileData || {}, cat = content.categories?.[p.problem]; return <><div className="feedback"><b>🗂️ جزئیات مسیر آرشیوشده</b><p className="muted">مسئله: {p.problem || '-'} · نام: {p.name || '-'} · کد: {p.code || '-'}</p><p className="muted">شروع: {formatDate(archive.startedAt)} · آرشیو: {formatDate(archive.archivedAt)}</p></div>{Object.entries(archive.answers || {}).sort(([x], [y]) => Number(x) - Number(y)).map(([d, ans]) => { const day = cat?.days?.find((x) => Number(x.day) === Number(d)); const daily = archive.daily?.[d]; return <div className="answerItem" key={d}><b>روز {fa(d)} · {String(day?.title || '').split('·')[0].trim()}</b><p>{ans}</p><small>شدت: {daily?.score == null ? '-' : `${fa(daily.score)} از ۱۰`} · {daily?.feedbackText || ''}</small></div>; })}<button className="secondary" onClick={onClose}>↩️ بازگشت به فهرست آرشیوها</button></>; }

export function BottomNav({ screen, onHome, onProfile, onBooks, onSupport }) {
  const active = screen === 'profile'
    ? 'profile'
    : ['books', 'bookReader'].includes(screen)
      ? 'books'
      : screen === 'support'
        ? 'support'
        : 'dashboard';
  return <nav className="bottomNav" id="bottomNav" aria-label="ناوبری اصلی"><button data-view="dashboard" className={active === 'dashboard' ? 'active' : ''} onClick={onHome}><span>⌂</span><b>خانه</b></button><button data-view="profile" className={active === 'profile' ? 'active' : ''} onClick={onProfile}><span>♙</span><b>پروفایل</b></button><button data-view="books" className={active === 'books' ? 'active' : ''} onClick={onBooks}><span>▤</span><b>مطالعه</b></button><button data-view="support" className={active === 'support' ? 'active' : ''} onClick={onSupport}><span>◌</span><b>ارتباط</b></button></nav>;
}
export function Footer() { return <div className="footer">مسیر ۲۸ روزه بازسازی ذهن<br/>مرکز هیپنوتراپی شفا<br/>برنامه آموزشی و خودمشاهده‌ای؛ جایگزین ارزیابی و درمان تخصصی نیست.</div>; }

export function CopyrightModal({ onAccept }) { return <div className="copyrightModal" id="copyrightModal"><div className="copyrightCard"><div className="copyrightIcon">🔒</div><h2>احترام به حقوق اثر</h2><p className="muted">محتوای کتاب‌ها، تمرین‌ها و مطالب آموزشی این برنامه متعلق به مرکز هیپنوتراپی شفا و صاحب اثر است و استفاده از آن برای کاربر مجاز برنامه در نظر گرفته شده است.</p><p className="muted">کپی، انتشار، بازنشر، فروش، ارسال برای دیگران یا استفاده تجاری از محتوای کتاب‌ها و مطالب برنامه بدون اجازه صاحب اثر مجاز نیست.</p><p className="muted">برای مطالعه و استفاده قانونی از آثار، لطفاً نسخه اصلی کتاب‌ها را از مرکز هیپنوتراپی شفا تهیه کنید.</p><button className="primary" onClick={onAccept}>{buttonLabel('متوجه شدم و ورود به مسیر را ادامه می‌دهم')}</button></div></div>; }
export function ValidationModal({ data, onClose }) { return <div className="validationModal" id="validationModal"><div className="validationCard"><span className="badge">تکمیل اطلاعات</span><h2 id="validationTitle">{data.title}</h2><p className="muted">موارد زیر را بررسی کن تا بتوانی ادامه بدهی:</p><ul id="validationList">{data.items.map((item, i) => <li key={`${item}-${i}`}>{item}</li>)}</ul><button className="primary" onClick={onClose}>{buttonLabel('متوجه شدم')}</button></div></div>; }
export function BookPreviewModal({ preview, onClose, onOpen }) { return <div className="bookPreviewModal" id="bookPreviewModal"><div className="bookPreviewCard"><span className="badge">مطالعه پیشنهادی · اختیاری</span><h2 id="bookPreviewTitle">📖 مطالعه پیشنهادی روز {fa(preview.day)}</h2><p className="muted" id="bookPreviewMeta">{preview.meta}</p><article className="bookPreviewText" id="bookPreviewText">{preview.text}</article><button className="primary" onClick={onOpen}>📚 رفتن به کتابخانه اختصاصی</button><button className="secondary" onClick={onClose}>↩️ فعلاً نمی‌خوانم</button></div></div>; }
